<?php
/**
 * Başkan modül yetkileri tanımları
 * Her modül benzersiz bir anahtar ile temsil edilir.
 */
return [
    // Başkan paneli modülleri (varsayılan: açık)
    'baskan_dashboard' => [
        'label' => 'Kontrol Paneli',
        'group' => 'Genel',
        'category' => 'uye',
        'default' => true,
        'description' => 'Tüm kullanıcılar için ortak kontrol paneli.',
        'icon' => 'fas fa-gauge-high',
    ],
    'baskan_uyeler' => [
        'label' => 'Üye Yönetimi',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'BYK’nıza bağlı üyeleri görüntüleyin ve filtreleyin.',
        'icon' => 'fas fa-people-group',
    ],
    'baskan_etkinlikler' => [
        'label' => 'Etkinlikler',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'BYK etkinliklerini oluşturun, düzenleyin ve takip edin.',
        'icon' => 'fas fa-calendar-day',
    ],
    'baskan_toplantilar' => [
        'label' => 'Toplantılar',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Toplantıları planlayın, gündem ve katılımcıları yönetin.',
        'icon' => 'fas fa-handshake-simple',
    ],
    'baskan_duyurular' => [
        'label' => 'Duyurular',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'BYK üyeleri ile paylaşılacak duyuruları hazırlayın.',
        'icon' => 'fas fa-bullhorn',
    ],
    'baskan_izin_talepleri' => [
        'label' => 'İzin Talepleri',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Üyelerden gelen izin taleplerini inceleyin ve yanıtlayın.',
        'icon' => 'fas fa-calendar-check',
    ],
    'baskan_harcama_talepleri' => [
        'label' => 'Harcama Talepleri',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Masraf taleplerini inceleyip onaylayın.',
        'icon' => 'fas fa-receipt',
    ],
    'baskan_iade_formlari' => [
        'label' => 'İade Formları',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Gönderilen iade formlarını görüntüleyin ve yönetin.',
        'icon' => 'fas fa-file-invoice-dollar',
    ],
    'baskan_raporlar' => [
        'label' => 'Raporlar',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'BYK performans raporlarını görüntüleyin.',
        'icon' => 'fas fa-chart-line',
    ],
    'baskan_demirbas_yonetimi' => [
        'label' => 'Demirbaş Yönetimi',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Demirbaş envanterini yönetin (Ekle/Sil/Düzenle).',
        'icon' => 'fas fa-boxes-stacked',
    ],
    'baskan_demirbas_talepleri' => [
        'label' => 'Demirbaş Talepleri',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Demirbaş taleplerini yönetin.',
        'icon' => 'fas fa-box',
    ],
    'baskan_raggal_talepleri' => [
        'label' => 'Raggal Talepleri',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Raggal rezervasyon taleplerini yönetin.',
        'icon' => 'fas fa-calendar-check',
    ],
    'baskan_projeler' => [
        'label' => 'Proje Yönetimi',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Projeleri oluşturun, görevleri ve ekipleri yönetin.',
        'icon' => 'fas fa-project-diagram',
    ],
    'baskan_sube_ziyaretleri' => [
        'label' => 'Şube Ziyaretleri',
        'group' => 'Baskan Paneli',
        'category' => 'baskan',
        'default' => true,
        'description' => 'Şube ziyaretlerini planlayın ve raporlayın.',
        'icon' => 'fas fa-map-location-dot',
    ],

    // Üye paneli modülleri (varsayılan: kapalı)
    'uye_duyurular' => [
        'label' => 'Üye Duyuruları',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'Üyelerle paylaşılan duyuru akışı.',
        'icon' => 'fas fa-bullhorn',
    ],
    'uye_etkinlikler' => [
        'label' => 'Üye Etkinlikleri',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'Üyelerin katılabileceği etkinlik listesi.',
        'icon' => 'fas fa-calendar-days',
    ],
    'uye_toplantilar' => [
        'label' => 'Üye Toplantıları',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'Üyelerin davetli olduğu toplantılar.',
        'icon' => 'fas fa-users',
    ],
    'uye_izin_talepleri' => [
        'label' => 'Üye İzin Talepleri',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'Kullanıcı kendi izin talebini oluşturabilir.',
        'icon' => 'fas fa-person-walking',
    ],
    'uye_harcama_talepleri' => [
        'label' => 'Üye Harcama Talepleri',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'Kullanıcının masraf talebi oluşturma ekranı.',
        'icon' => 'fas fa-wallet',
    ],
    'uye_iade_formu' => [
        'label' => 'Üye İade Formu',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'İade formu gönderme arayüzü.',
        'icon' => 'fas fa-file-circle-dollar',
    ],
    'uye_demirbas_talep' => [
        'label' => 'Demirbaş Talep',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'Demirbaş talep formu.',
        'icon' => 'fas fa-box',
    ],
    'uye_raggal_talep' => [
        'label' => 'Raggal Rezervasyon',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => false,
        'description' => 'Raggal rezervasyon formu.',
        'icon' => 'fas fa-calendar-plus',
    ],
    'uye_projeler' => [
        'label' => 'Projelerim',
        'group' => 'Üye Modülleri',
        'category' => 'uye',
        'default' => true,
        'description' => 'Dahil olduğunuz projeleri ve görevleri görüntüleyin.',
        'icon' => 'fas fa-list-check',
    ],
];

